name: doc
on:
  workflow_call:

jobs:
  docs-fmt:
    name: 'Check docs format'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: perses/github-actions@v0.10.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
      - name: install mdox
        run: go install github.com/bwplotka/mdox@latest
      - name: check docs
        run: make checkdocs
