name: react.yml
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  lint-pnpm:
    name: 'lint-pnpm'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - uses: perses/github-actions@v0.13.0
      - uses: pnpm/action-setup@v4
        with:
          version: 12.1.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm format:check
  test-pnpm:
    name: 'test-pnpm'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - uses: perses/github-actions@v0.13.0
      - uses: pnpm/action-setup@v4
        with:
          version: 12.1.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  type-check:
    name: 'type-check'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - uses: perses/github-actions@v0.13.0
      - uses: pnpm/action-setup@v4
        with:
          version: 12.1.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm type-check
